platform :ios, '12.0'
use_frameworks!
inhibit_all_warnings!

target 'Monsters' do

  # Pods for Monsters
  pod "RealmSwift", "3.17.0"
  pod 'TPKeyboardAvoiding', '1.3.2'
  pod 'SPStorkController', '1.6.5'
  pod 'lottie-ios'

  target 'MonstersTests' do
    inherit! :search_paths
    # Pods for testing
    pod "RealmSwift", "3.17.0"
    pod 'TPKeyboardAvoiding', '1.3.2'
    pod 'SPStorkController', '1.6.5'
    pod 'lottie-ios'
  end

end
